---
- name: Gather Kubernetes Cluster Info
  hosts: kube_control_plane
  tasks:
    - name: Get cluster information
      command: kubectl get node
      register: cluster_info_output

    - name: Display cluster information
      debug:
        var: cluster_info_output.stdout