---
- name: Create Kubernetes Namespace
  hosts: master-node-1
  gather_facts: no
  tasks:
    - name: Create a namespace in Kubernetes
      kubernetes.core.k8s:
        name: testingxxx
        api_version: v1
        kind: Namespace
        state: present