- name: "Check Status Service"
  hosts: "{{ host }}"
  tasks:
    - name: Check service status with systemctl
      shell: systemctl is-active crond || true
      register: service_status_service
      ignore_errors: yes

    - name: Display service status
      debug:
        msg: "Service status: {{service_status_service}}"
