---
- name: "Install Pre-Packages for Linux"
  hosts: "{{ host }}"

  become: true
  tasks:
    - name: "Install packages by list"
      apt:
        name:
          - net-tools
          - htop
        update_cache: yes
