---
- name: "Update apt Packages"
  hosts: "{{ host }}"
  become: true
  become_user: root

  tasks:
    - name: "Update and upgrade all packages"
      apt:
        update_cache: yes
        upgrade: yes
