---
- name: "Update apt Packages"
  hosts: "{{ host }}"

  become: true
  tasks:
    - name: "Update apt Packages"
      apt:
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time: 3600