---
- name: "Install Pre-Packages for Linux"
  hosts: "{{ hosts }}"

  become: true
  tasks:
    - name: "Install packages by list"
      apt:
        name:
          - net-tools
          - htop
          - vim
          - nfs-common
        update_cache: yes
